//
// This is a file generated by Phase-Locked Loop wizard.
// Please do not edit this file!
// Generated time: 12/25/2015 18:13:58
// Version: Primace 7.3.1
// Wizard name: Phase-Locked Loop 1.0b
//
// ============================================================
// File Name: pll_v1.v
// IP core : pll
// Device name: M7A12N5F256C7
// ============================================================

module pll_v1(
    clkin0,
    clkout0,
    clkout1,
    locked
);

input clkin0;
output clkout0;
output clkout1;
output locked;

M7S_PLL #(
        .sel_fbpath (1'b0),
        .pll_fbck_del (4'b0000),
        .pll_sel ("auto"),
        .pwrmode (2'b01),
        .rst_pll_sel (2'b00),
        .pll_divm (8'b00111011),
        .pll_divn (8'b00000000),
        .pll_divc0 (8'b00000101),
        .pll_divc1 (8'b01100011),
        .pll_divc2 (8'b00000111),
        .pll_divc3 (8'b00000010),
        .pll_divmp (3'b000),
        .pll_mken0 (1'b1),
        .pll_mken1 (1'b1),
        .pll_mken2 (1'b0),
        .pll_mken3 (1'b0),
        .pll_bps0 (1'b0),
        .pll_bps1 (1'b0),
        .pll_bps2 (1'b0),
        .pll_bps3 (1'b0),
        .pll_co0dly (8'b00000000),
        .pll_co1dly (8'b00000000),
        .pll_co2dly (8'b00000000),
        .pll_co3dly (8'b00000000),
        .pll_sel_c0phase (3'b000),
        .pll_sel_c1phase (3'b000),
        .pll_sel_c2phase (3'b000),
        .pll_sel_c3phase (3'b000),
        .dyn_pll_rst (1'b0),
        .dyn_pll_pwrdown (1'b0),
        .pll_mp_autor_en (1'b0),
        .pll_lpf (2'b00),
        .pll_vrsel (2'b01),
        .pll_cpsel_cr (2'b11),
        .pll_cpsel_fn (3'b100),
        .pll_kvsel (2'b11),
        .pll_fldd (2'b11),
        .pll_force_lock (1'b0),
        .pll_atest_en (1'b0),
        .pll_dtest_en (1'b0),
        .pll_atest_sel (1'b0),
        .pll_dtest_sel (1'b0),
        .pll_bp_dvdd12 (1'b0),
        .pll_divfb (1'b0),
        .pll_cksel (1'b0),
        .pll_ck_switch_en (1'b0),
        .pll_lkd_tol (1'b0),
        .pll_lkd_hold (1'b0),
        .pll_ssen (1'b0),
        .pll_ssrg (2'b01),
        .pll_ssdivh (2'b00),
        .pll_ssdivl (8'b11000111),
        .pll_bk (2'b00),
        .amux_sel (6'b000000),
        .cfg_nc (3'b000),
        .cfg_ldo_cfg (5'b00000)
)
pll_u0 (
        .clkin0 (clkin0),
        .clkin1 (),
        .fbclkin (),
        .pwrdown (),
        .fp_pll_rst (),
        .ACTIVECK (),
        .CKBAD0 (),
        .CKBAD1 (),
        .clkout0 (clkout0),
        .clkout1 (clkout1),
        .clkout2 (),
        .clkout3 (),
        .locked (locked)
);

endmodule

// ============================================================
//                  pll Setting
//
// Warning: This part is read by Primace, please don't modify it.
// ============================================================
// Device          : M7A12N5F256C7
// Module          : pll_v1
// IP core         : pll
// IP Version      : 1

// AutoCalc        : true
// AutoSwitch      : false
// Bypass0         : false
// Bypass1         : false
// Bypass2         : false
// Bypass3         : false
// C0              : 5
// C1              : 99
// C2              : 7
// C3              : 2
// Clkin0Enable    : true
// Clkin1Enable    : false
// ClkinDefault    : 0
// Delay0          : 0
// Delay1          : 0
// Delay2          : 0
// Delay3          : 0
// DeskewMode      : None
// DivideMP        : 0
// Enable0         : true
// Enable1         : true
// Enable2         : false
// Enable3         : false
// InputFreq       : 20
// M               : 59
// N               : 0
// Phase0          : 0
// Phase1          : 0
// Phase2          : 0
// Phase3          : 0
// PllLocation     : auto
// PortActiveck    : false
// PortCkbad0      : false
// PortCkbad1      : false
// PortLocked      : true
// PowerMode       : always_on
// ResetMode       : ccb
// Simulation Files: 
// SpreadDivH      : 0
// SpreadDivL      : 199
// SpreadEnable    : false
// SpreadRatio     : 1
// Synthesis Files : 
// VcoDivide       : 1
